services:
  drivenops_db:
    image: postgres
    container_name: drivenops_db
    restart: always
    ports:
      - 1234:5432
    env_file:
      - back-end/.env
    volumes:
      - pg:/var/lib/lib/postgresql/data

  drivenops_app:
    container_name: drivenops_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - drivenops_db
    env_file:
      - back-end/.env

volumes:
  pg:
